#!/bin/bash

set -e

help_fn() {
  echo "Usage: hbuild --src <src_path> --container <enroot_container_name> --script <build_script_name>"
}

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  --src)
    src_path=$2
    shift 2
    ;;
  --container)
    container_name=$2
    shift 2
    ;;
  --script)
    build_script=$2
    shift 2
    ;;
  -h | --help)
    help_fn
    exit
    ;;
  -*)
    echo "[hbuild] unknown option \"${key}\""
    exit
    ;;
  esac
done

srun -N 1 --cpus-per-task 32 --pty \
  enroot start --rw --root -m ${src_path}:/herring ${container_name} \
  bash -c "cd /herring && bash ${build_script}"
