#!/bin/bash

set -e

help_fn() {
  echo "Usage: hrun -N <num_nodes> --container <pyxis_container_name> <command-to-run-with-smddprun>"
}

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  -N | --nodes)
    num_nodes=$2
    shift 2
    ;;
  --container)
    container_name=$2
    shift 2
    ;;
  -h | --help)
    help_fn
    exit
    ;;
  *)
    break
    ;;
  esac
done

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

salloc -N $num_nodes --exclusive bash exec_inside_alloc.sh -N $num_nodes --container $container_name --script_dir $script_dir $@
