#!/bin/bash

set -e

help_fn() {
  echo "Usage: pcrun -N <num_nodes> --container <pyxis_container_name> <command-to-run-with-smddprun>"
}

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  -N | --nodes)
    num_nodes=$2
    shift 2
    ;;
  --container)
    container_name=$2
    shift 2
    ;;
  -h | --help)
    help_fn
    exit
    ;;
  *)
    echo $@
    break
    ;;
  esac
done

echo "out"

tasks_per_node=8
num_tasks=$((tasks_per_node*num_nodes))
export OMPI_MCA_btl_tcp_if_exclude="docker0,lo"
export PMIX_MCA_gds=hash

num_cpus=`srun -N 1 lscpu -p | tail -n 1 | cut -d ',' -f1`
num_cpus=$((num_cpus+1))
num_cpus_per_task=$((num_cpus/tasks_per_node))

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
srun -N $num_nodes -n $num_tasks --container-name ${container_name} \
  --container-mount-home --no-container-remap-root --container-workdir $HOME \
  --container-mounts ${script_dir}:/pcscripts,/scratch:/scratch,/fsx:/fsx \
  --cpus-per-task ${num_cpus_per_task} --mpi=pmix /pcscripts/runwithenvvars \
  smddprun -c /opt/conda $@

